# Site
name: "Votehub"
title: "Votehub"
description: "An advocacy platform for every Filipino's right to vote<br><h3>Do you have interesting stories about election or voting, share it with us!</h3>"
logo: 'assets/images/votehub.svg'
favicon: 'assets/images/votehub.svg'
baseurl: /
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: decastrodanield@gmail.com

# Authors
authors:
  daniel:
    name: Daniel
    display_name: Daniel
    email: votehub@mailinator.com
    web: https://danieldecastro.tech
    description: "just another person"
  argie:
    name: Argie
    display_name: "Argie Silang"
    email: votehub@mailinator.com
    web: https://web.facebook.com/argie.silang
    description: "just another person"
  maurine:
    name: Maurine
    display_name: "Maurine Joy Lopez"
    email: votehub@mailinator.com
    web: https://web.facebook.com/mauilopez.23
    description: "just another person"
  freshten:
    name: Freshten
    display_name: "Freshten Rosales"
    email: votehub@mailinator.com
    web: https://web.facebook.com/freshten.rosales
    description: "just another person"
  mark:
    name: Mark
    display_name: "Mark Seth Pita"
    email: votehub@mailinator.com
    web: https://web.facebook.com/spita27
    description: "just another person"
  aira:
    name: Aira
    display_name: "Aira Claveria"
    email: votehub@mailinator.com
    web: https://duckduckgo.com/?q=aira%20claveria
    description: "just another person"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
